//===========================================================================
// $Header$
//
//    (C) Copyright 2007 by Autodesk, Inc.
//
// The information contained herein is confidential, proprietary
// to Autodesk, Inc., and considered a trade secret as defined 
// in section 499C of the penal code of the State of California.  
// Use of this information by anyone other than authorized employees
// of Autodesk, Inc. is granted only under a written non-disclosure 
// agreement, expressly prescribing the scope and manner of such use.       
//
// CREATED BY:
//      Norm Olsen
//
// DESCRIPTION:
//

#include "csConsoleUtilities.hpp"

extern "C" unsigned long KcsNmInvNumber;
extern "C" unsigned long KcsNmMapNoNumber;

// This module generates a test file in the OsGeo MetaCrs format.
// The test data is generated by user a specific version of the CS-MAP
// library, to be used.

//Generate a list:
//Traverse the coordinate system file.
// For each coordinate system, we extract the useful range in lat/longs
// We look at the remainder of the list of coordinate systems looking for an overlap in useful range.
// We then make a test case using the mid point of the intersection of the ranges.
// For this to work, we need to have a useful range for each definition.
 
 